theme: jekyll-theme-cayman
show_downloads: true
title: Dwains Lovelace Dashboard
google_analytics: UA-105338324-4
buttons:
  zip_url: https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases
  zip_title: Download latest version
  zip_hide: false
  tar_hide: true
